### ✏️ 에러 처리(error handing)의 필요성

에러가 발생하지 않는 코드를 작성하는 것은 불가능하기 때문에 에러는 언제나 발생할 수 있다. 발생한 에러에 대해 대처하지 않고 방치하면 프로그램은 강제 종료된다.

### ✏️ try…catch…finally문

기본적으로 에러 처리를 구현하는 방법은 크게 2가지가 있다.

- 예외적인 상항 발생 시 반환하는 값을 if문, 단축평가, 옵셔널 체이닝 연산자를 통해 확인하여 처리하는 방법
- 에러 처리코드를 등록해 두고 에러 발생 시 에러 처리 코드로 점프하는 방법
  → ex. `try…catch..finally`

```jsx
try {
  // 실행할 코드
  foo();
} catch (err) {
  // try 코드 블록에서 에러 발생 시 이 코드 블록 실행
  console.log(err);
} finally {
  // 에러 유무와 상관없이 1번 실행
  console.log('finally');
}
```

### ✏️ Error 객체

`Error` 생성자 함수는 에러 객체를 생성하며 에러를 상세히 설명하는 에러 메시지를 인수로 전달할 수 있다. 자바스크립트는 `Error` 생성자 함수를 포함해 7가지의 에러 객체를 생성할 수 있는 `Error` 생성자 함수를 제공한다.

```jsx
const error = new Error('invalid');
```

| Error          | 일반적 에러 객체                                                           |
| -------------- | -------------------------------------------------------------------------- |
| SyntaxError    | 자바스크립트 문법에 맞지 않는 문을 해석할 때 발생하는 에러 객체            |
| ReferenceError | 참조할 수 없는 식별자를 참조했을 때 발생하는 에러 객체                     |
| TypeError      | 피연산자나 인수의 데이터 타입이 유효하지 않을 때 발생하는 에러 객체        |
| RangeError     | 숫자 값의 허용 범위를 벗어났을 때 발생하는 에러 객체                       |
| URIError       | encodeURI, decodeURI 함수에 부적절한 인수를 전달했을 때 발생하는 에러 객체 |
| EvalError      | eval()에서 발생하는 에러 객체                                              |

### ✏️ throw문

에러 객체 생성과 에러 발생은 의미가 다르다. 에러를 발생시키려면 `try` 코드 블록에서 `throw` 문으로 에러 객체를 던져야 한다.

```jsx
try {
  // 에러 객체를 던지면 catch 코드 블록이 실행되기 시작한다.
  throw new Error('something wrong');
} catch (error) {
  console.log(error); // Error: something wrong
}
```

### ✏️ 에러의 전파

에러는 호출자(caller) 방향으로 전파되는데 콜 스택의 아래 방향(실행 중인 실행 컨텍스트가 푸시되기 직전에 푸시된 실행 컨텍스트 방향)으로 전파된다.

```jsx
const foo = () => {
  throw Error('fooError'); // [4]
};
const bar = () => {
  foo(); // [3]
};
const baz = () => {
  bar(); // [2]
};
try {
  baz(); // [1]
} catch (err) {
  console.log(err);
}
```

[1] `baz()` 호출 → [2] `bar()` 호출 → [3] `foo()` 호출 → [4] `Error throw` : `foo()`가 `throw`한 에러는 호출자에게 전파되어 전역에서 캐치된다.

비동기 함수, 프로미스 후속 처리 메서드의 콜백 함수는 실행 컨텍스트가 삭제되고 비동기 함수가 동작하기 때문에 호출자가 없고 그렇기 때문에 에러 처리가 힘들다.
